blank_issues_enabled: false
contact_links:
    - name: Feature request, support questions, and other
      url: https://github.com/balboacodes/stringable/discussions
      about: 'For feature requests, support, and other start a new discussion'
