name: pull request

on:
    pull_request:
        branches:
            - main
        types:
            - ready_for_review

permissions:
    contents: write

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v5

            - name: Install dependencies
              run: npm ci

            - name: Execute tests
              run: npm run test

            - name: Format
              run: npm run format

            - uses: autofix-ci/action@v1
              with:
                  commit-message: 'ci: apply formatting'
