name: pull request

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v5

            - name: Install dependencies
              run: npm ci

            - name: Format
              run: npm run format

            - name: Execute tests
              run: npm run test
